AppVg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("backoffice/", include("backoffice.urls")),
    path("", include("website.urls")),
]

backoffice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import views, quotation_views, client_views, equipment_views, pool_views, address_views, contact_views, \
    user_views

urlpatterns = [
    path('test/', login_required(views.test), name='test'),

    path('', login_required(views.dashboard), name='dashboard'),
    path('clients/', login_required(client_views.clients), name='clients'),
    path('new_client/', login_required(client_views.new_client), name='new_client'),
    path('clients/<int:client_id>/', login_required(client_views.client_details), name='client_details'),
    path('clients/<int:client_id>/edit', login_required(client_views.edit_client), name='edit_client'),
    path('clients/<int:client_id>/new_address/', login_required(address_views.new_address_client), name='new_address_client'),
    path('clients/<int:client_id>/new_contact/', login_required(contact_views.new_contact_client), name='new_contact_client'),

    path('equipments/', login_required(equipment_views.equipments), name='equipments'),
    path('new_equipment/', login_required(equipment_views.new_equipment), name='new_equipment'),
    path('equipments/<int:equipment_id>/edit', login_required(equipment_views.edit_equipment), name='edit_equipment'),

    path('quotations/', login_required(quotation_views.quotations), name='quotations'),
    path('new_quotation/<int:client_id>', login_required(quotation_views.new_quotation), name='new_quotation'),
    path('quotations/<int:quotation_id>/', login_required(quotation_views.quotation_details), name='quotation_details'),
    path('print_quotation/<int:quotation_id>/', login_required(quotation_views.print_quotation), name='print_quotation'),
    path('quotation/<int:quotation_id>/edit/', login_required(quotation_views.edit_quotation), name='edit_quotation'),
    path('quotation/<int:quotation_id>/delete/', login_required(quotation_views.quotation_delete), name='quotation_delete'),

    path('pools/', login_required(pool_views.pools), name='pools'),
    path('new_pool/', login_required(pool_views.new_pool), name='new_pool'),
    path('pools/<int:pool_id>/', login_required(pool_views.pool_details), name='pool_details'),
    path('clients/<int:client_id>/new_pool/', login_required(pool_views).new_pool_client, name='new_pool_client'),

    path("login", auth_views.LoginView.as_view(template_name="login/login.html"), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backoffice/models/client.py
from django.db import models


class Client(models.Model):
    client = models.IntegerField()
    name = models.CharField(max_length=100)
    fiscal_name = models.CharField(max_length=100)
    tax_number = models.CharField(max_length=20)
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


CONTACT_TYPE = (
    ('phone', 'Telemovel'),
    ('email', 'Email'),
)


class Contact(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    type = models.CharField(max_length=20, choices=CONTACT_TYPE, default='phone')
    contact = models.CharField(max_length=20, blank=True)
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.contact


class Address(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    street = models.CharField(max_length=100)
    number = models.CharField(max_length=10)
    city = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=10)
    coordinate_x = models.DecimalField(max_digits=9, decimal_places=6)
    coordinate_y = models.DecimalField(max_digits=9, decimal_places=6)
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.street} {self.number}, {self.city}, {self.postal_code}"

backoffice/models/equipment.py
from django.db import models


class Equipment(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='equipment/')
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

backoffice/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    class Role(models.TextChoices):
        ADMIN = "ADMIN", 'Admin'
        OFFICE = "OFFICE", 'Escritório'
        TECHNICIAN = "TECHNICIAN", 'Técnico'

    role = models.CharField(max_length=100, choices=Role.choices)
    phone_number = models.CharField(max_length=20, blank=True)

backoffice/forms.py
from bootstrap_datepicker_plus.widgets import DatePickerInput
from django import forms
from django.forms import inlineformset_factory, CheckboxSelectMultiple, DateInput
from django.shortcuts import get_object_or_404

from backoffice.models.client import Client, Address, Contact
from backoffice.models.equipment import Equipment
from backoffice.models.pool import Pool
from backoffice.models.quotation import Quotation
from django_select2 import forms as Select2Forms


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['client', 'name', 'fiscal_name', 'tax_number', 'notes']
        widgets = {
            'client': forms.TextInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'fiscal_name': forms.TextInput(attrs={'class': 'form-control'}),
            'tax_number': forms.TextInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }


class AddressForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        client = kwargs.pop('client', None)
        super().__init__(*args, **kwargs)

        if client:
            self.fields['client'].widget = forms.HiddenInput()
            self.fields['client'].initial = client

    class Meta:
        model = Address
        fields = ('client', 'street', 'number', 'city', 'postal_code', 'coordinate_x', 'coordinate_y', 'notes')
        widgets = {
            'street': forms.TextInput(attrs={'class': 'form-control'}),
            'number': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
            'coordinate_x': forms.NumberInput(attrs={'class': 'form-control'}),
            'coordinate_y': forms.NumberInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }


class ContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        client = kwargs.pop('client', None)
        super().__init__(*args, **kwargs)

        if client:
            self.fields['client'].widget = forms.HiddenInput()
            self.fields['client'].initial = client

    class Meta:
        model = Contact
        fields = ['client', 'type', 'contact', 'notes']
        widgets = {
            'type': forms.Select(attrs={'class': 'form-select'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }


class EquipmentForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = ['name', 'description', 'image', 'price']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }


class PoolForm(forms.ModelForm):
    class Meta:
        model = Pool
        fields = [
            'address',
            'length',
            'width',
            'min_depth',
            'max_depth',
            'circulation_type',
        ]

    def __init__(self, *args, addresses=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        self.fields['length'].widget.attrs.update({'class': 'form-control'})
        self.fields['width'].widget.attrs.update({'class': 'form-control'})
        self.fields['min_depth'].widget.attrs.update({'class': 'form-control'})
        self.fields['max_depth'].widget.attrs.update({'class': 'form-control'})
        self.fields['circulation_type'].widget.attrs.update({'class': 'form-control'})
        if addresses:
            self.fields['address'].queryset = addresses


class QuotationForm(forms.ModelForm):
    """
        client_address = forms.ModelChoiceField(queryset=Address.objects.none())
        client_phone = forms.ModelChoiceField(queryset=Contact.objects.none())
        client_email = forms.ModelChoiceField(queryset=Contact.objects.none())
    """

    equipments = forms.ModelMultipleChoiceField(queryset=Equipment.objects.all(),
                                                widget=Select2Forms.Select2MultipleWidget)
    extra_recommendations = forms.ModelMultipleChoiceField(queryset=Equipment.objects.all(),
                                                           widget=Select2Forms.Select2MultipleWidget)
    date = forms.DateField(widget=DatePickerInput())

    def __init__(self, *args, **kwargs):
        client = kwargs.pop('client', None)
        quotation = kwargs.pop('quotation', None)
        super().__init__(*args, **kwargs)

        if client:
            self.fields['client'].widget = forms.HiddenInput()
            self.fields['client'].initial = client
            self.initial['client'] = client
            self.fields['client_address'].queryset = Address.objects.filter(client=client)
            self.fields['client_phone'].queryset = Contact.objects.filter(client=client, type='phone')
            self.fields['client_email'].queryset = Contact.objects.filter(client=client, type='email')
            self.fields['pool'].queryset = Pool.objects.filter(
                address__in=Address.objects.filter(client=client)
            )

        if quotation:
            self.fields['client_address'].queryset = Address.objects.filter(client=quotation.client)
            self.fields['client_phone'].queryset = Contact.objects.filter(client=quotation.client, type='phone')
            self.fields['client_email'].queryset = Contact.objects.filter(client=quotation.client, type='email')
            self.initial['client_address'] = quotation.client_address
            self.initial['client_phone'] = quotation.client_phone
            self.initial['client_email'] = quotation.client_email

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('client_address'):
            self.add_error('client_address', 'Please select a client address.')
        if not cleaned_data.get('equipments'):
            self.add_error('equipments', 'Please select at least one equipment.')
        return cleaned_data

    class Meta:
        model = Quotation
        fields = ('quotation_type', 'client', 'client_address', 'client_phone', 'client_email', 'equipments', 'pool',
                  'date', 'greetings', 'extra_recommendations', 'comments', 'transportation_fee', 'labor_rate',
                  'status')

backoffice/views/address_views.py
from django.shortcuts import render, redirect, get_object_or_404

from backoffice.forms import AddressForm
from backoffice.models.client import Client


def new_address_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)

    if request.method == 'POST':
        form = AddressForm(request.POST, client=client)
        if form.is_valid():
            address = form.save(commit=False)
            address.client = client
            address.save()
            return redirect('client_details', client_id=client_id)
    else:
        form = AddressForm(client=client)

    context = {
        'form': form,
        'client': client
    }
    return render(request, 'client/new_address.html', context)

backoffice/views/client_views.py
from django.shortcuts import render, redirect, get_object_or_404

from backoffice.forms import ClientForm
from backoffice.models.client import Client


def clients(request):
    clientsList = Client.objects.all()

    context = {
        'clients': clientsList,
    }
    return render(request, 'client/clients.html', context)


def new_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clients')
    else:
        form = ClientForm()
    return render(request, 'client/new_client.html', {'form': form})


def client_details(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    addresses = client.address_set.all()
    quotations = client.quotation_set.all()
    pools = []
    for address in addresses:
        for pool in address.pools.all():
            pools.append(pool)

    context = {
        'client': client,
        'addresses': addresses,
        'quotations': quotations,
        'pools': pools
    }
    return render(request, 'client/client_details.html', context)


def edit_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    context = {
        'client': client,
    }
    return render(request, 'client/edit_client.html', context)

backoffice/views/contact_views.py
from django.shortcuts import render, redirect, get_object_or_404

from backoffice.forms import ClientForm, AddressForm, ContactForm
from backoffice.models.client import Client, Contact, Address
from backoffice.models.pool import Pool


def new_contact_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)

    if request.method == 'POST':
        form = ContactForm(request.POST, client=client)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.client = client
            contact.save()
            return redirect('client_details', client_id=client_id)
    else:
        form = ContactForm(client=client)

    context = {
        'form': form,
        'client': client
    }
    return render(request, 'client/new_contact.html', context)

backoffice/views/equipment_views.py
from django.shortcuts import render, redirect, get_object_or_404

from backoffice.forms import EquipmentForm
from backoffice.models.equipment import Equipment


def equipments(request):
    equipmentsList = Equipment.objects.all()

    context = {
        'equipments': equipmentsList,
    }
    return render(request, 'equipment/equipments.html', context)


def new_equipment(request):
    if request.method == 'POST':
        form = EquipmentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('equipments')
    else:
        form = EquipmentForm()
    return render(request, 'equipment/new_equipment.html', {'form': form})


def edit_equipment(request, equipment_id):
    equipment = get_object_or_404(Equipment, id=equipment_id)

    if request.method == 'POST':
        form = EquipmentForm(request.POST, request.FILES, instance=equipment)
        if form.is_valid():
            form.save()
            return redirect('equipments')
    else:
        form = EquipmentForm(instance=equipment)

    return render(request, 'equipment/edit_equipment.html', {'form': form})

backoffice/views/pool_views.py
from django.shortcuts import render, redirect, get_object_or_404

from backoffice.forms import PoolForm
from backoffice.models.client import Client
from backoffice.models.pool import Pool


def pools(request):
    poolList = Pool.objects.all()
    context = {'pools': poolList}
    return render(request, 'pool/pools.html', context)


def new_pool(request):
    if request.method == 'POST':
        form = PoolForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pools')
    else:
        form = PoolForm()

    context = {
        'form': form
    }

    return render(request, 'pool/new_pool.html', context)


def new_pool_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    addresses = client.address_set.all()
    if request.method == 'POST':
        form = PoolForm(request.POST)
        if form.is_valid():
            pool = form.save(commit=False)
            pool.address = client.address_set.first()
            pool.save()
            return redirect('new_quotation', client_id=client.id)
    else:
        form = PoolForm(addresses=addresses)

    context = {
        'form': form,
        'client': client,
        'addresses': addresses,
    }
    return render(request, 'pool/new_pool_client.html', context)


def pool_details(request, pool_id):
    pool = get_object_or_404(Pool, id=pool_id)
    context = {
        'pool': pool,
    }
    return render(request, 'pool/pool_details.html', context)

backoffice/views/user_views.py
from django.contrib.auth import logout
from django.shortcuts import redirect


def logout_view(request):
    logout(request)
    return redirect('index')

backoffice/views/views.py
from django.shortcuts import render


def dashboard(request):
    context = {
        'user': request.user
    }
    return render(request, 'dashboard.html', context)


def test(request):
    context = {
        'user': request.user
    }
    return render(request, 'test.html', context)

backoffice/templates/client/client_details.html
{% extends "base.html" %}

{% block content %}

    <div class="row align-items-center mb-3">
        <div class="col">
            <h1 class="mb-0">Detalhes do Cliente</h1>
        </div>
        <div class="col text-end">
            <a href="{% url 'edit_client' client_id=client.id %}" class="btn btn-success float-right">Editar</a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2>{{ client.name }} - {{ client.fiscal_name }}</h2>
            <p class="mb-2">NIF: {{ client.tax_number }}</p>
            <p>Comentários: {{ client.notes }}</p>
        </div>
    </div>

    <div class="row m-5">
        <div class="d-flex justify-content-between">
            <div class="">
                <h3>Contactos</h3>
            </div>
            <div class="">
                <a href="{% url 'new_contact_client' client_id=client.id %}" class="btn btn-success float-right">Adicionar
                    Contacto</a>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Tipo</th>
                <th>Contacto</th>
                <th>Comentários</th>
            </tr>
            </thead>
            <tbody>
            {% for contact in client.contact_set.all %}
                <tr>
                    <td>{{ contact.type }}</td>
                    <td>{{ contact.contact }}</td>
                    <td>{{ contact.notes }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2">Não existem contactos.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row m-5">
        <div class="d-flex justify-content-between">
            <div>
                <h3>Moradas</h3>
            </div>
            <div>
                <a href="{% url 'new_address_client' client_id=client.id %}" class="btn btn-success float-right">Adicionar
                    Morada</a>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Morada</th>
                <th>Coordenadas</th>
                <th>Comentários</th>
            </tr>
            </thead>
            <tbody>
            {% for address in addresses %}
                <tr>
                    <td>{{ address }}</td>
                    <td>{{ address.coordinate_x }}, {{ address.coordinate_y }}</td>
                    <td>{{ address.notes }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">Não existem contactos.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row m-5">
        <div class="d-flex justify-content-between">
            <div>
                <h3>Piscinas</h3>
            </div>
            <div>
                <a href="{% url 'new_pool_client' client_id=client.id %}" class="btn btn-success float-right">Adicionar
                    Piscina</a>

            </div>
        </div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Morada</th>
                <th>Comprimento</th>
                <th>Largura</th>
                <th>Profundidade Mínima</th>
                <th>Profundidade Máxima</th>
                <th>Tipo de Circulação</th>
            </tr>
            </thead>
            <tbody>
            {% for pool in pools %}
                <tr>
                    <td>{{ pool.address }}</td>
                    <td>{{ pool.length }}</td>
                    <td>{{ pool.width }}</td>
                    <td>{{ pool.min_depth }}</td>
                    <td>{{ pool.max_depth }}</td>
                    <td>{{ pool.circulation_type }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">No pools found.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row m-5">
        <div class="d-flex justify-content-between">
            <div>
                <h3>Propostas</h3>
            </div>
            <div>
                <a href="{% url 'new_quotation' client_id=client.id %}" class="btn btn-success float-right">Criar
                    Proposta</a>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>Client</th>
                <th>Address</th>
                <th>Comments</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody>
            {% for quotation in quotations %}
                <tr>
                    <td><a href="{% url 'quotation_details' quotation.id %}">{{ quotation.id }}</a></td>
                    <td>{{ quotation.client }}</td>
                    <td>{{ quotation.pool }}</td>
                    <td>{{ quotation.comments }}</td>
                    {% if quotation.status == "draft" %}
                        <td class="table-cell-blue">{{ quotation.status }}</td>
                    {% elif quotation.status == "sent" %}
                        <td class="table-cell-yellow">{{ quotation.status }}</td>
                    {% elif quotation.status == "approved" %}
                        <td class="table-cell-green">{{ quotation.status }}</td>
                    {% elif quotation.status == "rejected" %}
                        <td class="table-cell-red">{{ quotation.status }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

backoffice/templates/client/clients.html
{% extends "base.html" %}
{% block content %}

    <h1>Client List</h1>
    <table class="table table-striped-columns table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Fiscal Name</th>
            <th>Address</th>
        </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr style='cursor: pointer; cursor: hand;' onclick="window.location='{% url 'client_details' client.id %}';">
                <td>{{ client.client }}</td>
                <td>{{ client.name }}</td>
                <td>{{ client.fiscal_name }}</td>
                <td>{{ client.address_set.first.street }} {{ client.address_set.first.number }},
                    {{ client.address_set.first.city }}, {{ client.address_set.first.postal_code }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <script>
        $(document).ready(function () {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

backoffice/templates/client/edit_client.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Client</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-primary">
        <a href="{% url 'client_details' client_id=client.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

backoffice/templates/client/new_address.html
{% extends "base.html" %}

{% block content %}
    <h1>Nova Morada</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

    <a href="{% url 'client_details' client_id=client.id %}">Voltar para Cliente</a>
{% endblock %}

backoffice/templates/client/new_client.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}
        <div class="alert alert-danger">{{ error_message }}</div>
    {% endif %}
    <h1>Create New Client</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success">Create Client</button>
    </form>
{% endblock %}

backoffice/templates/client/new_contact.html
{% extends "base.html" %}

{% block content %}
    <h1>Novo Contacto</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

    <a href="{% url 'client_details' client_id=client.id %}">Voltar para Cliente</a>
{% endblock %}